### PR TITLE
fix(vscode): preserve packaged Playwright runtime

### PR DESCRIPTION
**Pull request by marius-kilocode**
## What Problem This Solves

Fix the installed-extension activation regression introduced by #13501. A snapshot built from main fails before `activate()` with `Cannot find module '../../../package.json'`, leaving the Kilo sidebar empty while its toolbar remains visible.

Playwright resolves its package manifest relative to its own runtime files. Bundling those files into `dist/extension.js` changes that lookup to an ancestor outside the extension. Development can hide the error because the same path finds the monorepo's root manifest.

## Why This Change Was Made

Keep Playwright external to the extension bundle and copy its runtime package, Chromium BiDi, and their pinned runtime dependencies into `dist/node_modules`. Preserve package resources and dependency resolution without copying workspace dependency symlinks. The existing VSIX rules include this directory even when packaging with `--no-dependencies`.

The regression test builds the real browser broker, applies VSCE's file selection, copies only the selected files into an installation directory outside the repository, and loads it in a separate Node process with global module search disabled. It checks that Playwright resolves inside the installation and that required runtime assets ship.

## User Impact

Installed snapshots can activate and display the sidebar and Settings again. Browser automation retains a working Playwright runtime rather than relying on a substitute manifest or a path workaround.

Copying runs at build time. Playwright still loads eagerly at the existing startup point; the change from bundled code to separate package files has not been benchmarked, so this PR makes no startup-time guarantee.

## Evidence

- Extension unit suite: 4,560 passed, 1 skipped, 0 failed.
- Production package build, host/webview typechecks, lint, formatting, Knip, and the package marker guard passed.
- Installed the production VSIX into an isolated VS Code profile outside the repository, with separate Kilo data. The sidebar and Settings rendered successfully on macOS.
- Loaded Playwright from that installed VSIX, launched headless Chrome, and read test page content successfully.
- The final diff contains only the runtime packaging fix, its regression test, and a changeset. No screenshots or binaries are committed to this repository.

Kilo sidebar renders its welcome screen and prompt input after installing the fixed VSIX

### CODE REVIEW

File: packages/kilo-vscode/script/playwright-runtime.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
+const fs = require("node:fs")
```
Comment (WebReflection) [inline packages/kilo-vscode/script/playwright-runtime.js:1]: just a question: is there any particular reason this file uses CommonJS instead of ES Module?

File: packages/kilo-vscode/esbuild.js [hunk 2]
```diff
@@ -5,6 +5,7 @@ const crypto = require("crypto")
 const core = require("@babel/core")
 const solid = require("babel-preset-solid")
 const ts = require("@babel/preset-typescript")
+const playwright = require("./script/playwright-runtime")
```
Comment (WebReflection) [inline packages/kilo-vscode/esbuild.js:8]: never mind, this answers my previous question!

**Review by WebReflection — APPROVED** [review]
