### PR TITLE
feat(provider): add gemini cli 3.0 pro preview  support

### PR DESCRIPTION
**Pull request by Sn0wo2**
## Context

add gemini cli 3.0 pro model support

## Implementation

https://github.com/google-gemini/gemini-cli/commit/56f9e597c69fd65e9971d69ba0b15457189e67ec

https://ai.google.dev/gemini-api/docs/gemini-3

### CODE REVIEW

**Comment by kevinvandijk** [comment]
Have you seen this working as well? I can't get it to work locally even though I have the cli settings set to include preview features like gemini 3.

**Comment by Sn0wo2** [comment]
> Have you seen this working as well? I can't get it to work locally even though I have the cli settings set to include preview features like gemini 3.

https://github.com/google-gemini/gemini-cli/blob/release/v0.16.0-preview.5/docs/get-started/gemini-3.md
gemini-3.0-pro-preview is not currently in the free tier of the cli...
Unfortunately, I dont have a Google AI Ultra subscriber, but I have submitted an application for gemini 3 pro

```
> hello                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                  █
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                                                                                 │
│ It seems like you don't have access to Gemini 3.                                                                                                                                                                                                │
│ Learn more at https://goo.gle/enable-preview-features                                                                                                                                                                                           │
│ To disable Gemini 3, disable "Preview features" in /settings.                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                 │
│                                                                                                                                                                                                                                                 │
│ ● 1. Switch to gemini-2.5-pro                                                                                                                                                                                                                   │
│   2. Stop                                                                                                                                                                                                                                       │
│                                                                                                                                                                                                                                                 │
│ Note: You can always use /model to select a different option.                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

```

**Comment by art13eck** [comment]
Screenshot_5
there is no new model :[

**Comment by Sn0wo2** [comment]
> Screenshot_5 there is no new model :[

This PR hasnt been merged yet, so you dont see Gemini CLI 3.0 Pro in the latest version

File: packages/types/src/providers/gemini-cli.ts [hunk 1]
```diff
@@ -108,4 +108,15 @@ export const geminiCliModels = {
 		supportsReasoningBudget: true,
 		requiredReasoningBudget: true,
 	},
+    "gemini-3.0-pro-preview": {
```
Comment (jgbpve) [inline packages/types/src/providers/gemini-cli.ts]: The model ID here should be gemini-3-pro-preview (no .0).

With gemini-3.0-pro-preview I get a "404 Requested entity was not found", but gemini-3-pro-preview works and matches the official docs: [https://ai.google.dev/gemini-api/docs/models](https://ai.google.dev/gemini-api/docs/models)

**Comment by Mirrowel** [comment]
This just adds the model - this can't work.
Gemini 3 needs thought signatures stored with the message history and sent back.
You can skip that, but that is just a waste of gemini 3. And it still needs to be coded either way.

**Comment by Sn0wo2** [comment]
> This just adds the model - this can't work. Gemini 3 needs thought signatures stored with the message history and sent back. You can skip that, but that is just a waste of gemini 3. And it still needs to be coded either way.

Its frustrating that Google still doesnt pass my Gemini 3 Pro whitelist, so I cant test it either, and I will close this PR if anyone else plans to add Gemini 3 Pro in cli

**Comment by Mirrowel** [comment]
> > This just adds the model - this can't work. Gemini 3 needs thought signatures stored with the message history and sent back. You can skip that, but that is just a waste of gemini 3. And it still needs to be coded either way.
> 
> Its frustrating that Google still doesnt pass my Gemini 3 Pro whitelist, so I cant test it either, and I will close this PR if anyone else plans to add Gemini 3 Pro in cli

I got it in 3 hours after i got my pro for a year. Try submitting again.

**Comment by mcowger** [comment]
This PR doesn't work for me.

Confirmed I have 3.0 Preview Access:
Screenshot 2025-11-26 at 12 34 46 PM

Confirmed GeminiCLI works with 2.5 Flash

Screenshot 2025-11-26 at 12 35 37 PM

Switch to pro preview:

Screenshot 2025-11-26 at 12 36 17 PM

**Comment by Sn0wo2** [comment]
> This PR doesn't work for me.
> 
> Confirmed I have 3.0 Preview Access: Screenshot 2025-11-26 at 12 34 46 PM
> 
> Confirmed GeminiCLI works with 2.5 Flash
> 
> Screenshot 2025-11-26 at 12 35 37 PM
> Switch to pro preview:
> 
> Screenshot 2025-11-26 at 12 36 17 PM

It is worth mentioning that they added `ensureActiveLoopHasThoughtSignatures` for preview model https://github.com/google-gemini/gemini-cli/commit/56f9e597c69fd65e9971d69ba0b15457189e67ec
```
  // To ensure our requests validate, the first function call in every model
  // turn within the active loop must have a `thoughtSignature` property.
  // If we do not do this, we will get back 400 errors from the API.
  ensureActiveLoopHasThoughtSignatures(requestContents: Content[]): Content[] {
    // First, find the start of the active loop by finding the last user turn
    // with a text message, i.e. that is not a function response.
    let activeLoopStartIndex = -1;
    for (let i = requestContents.length - 1; i >= 0; i--) {
      const content = requestContents[i];
      if (content.role === 'user' && content.parts?.some((part) => part.text)) {
        activeLoopStartIndex = i;
        break;
      }
    }

    if (activeLoopStartIndex === -1) {
      return requestContents;
    }

    // Iterate through every message in the active loop, ensuring that the first
    // function call in each message's list of parts has a valid
    // thoughtSignature property. If it does not we replace the function call
    // with a copy that uses the synthetic thought signature.
    const newContents = requestContents.slice(); // Shallow copy the array
    for (let i = activeLoopStartIndex; i < newContents.length; i++) {
      const content = newContents[i];
      if (content.role === 'model' && content.parts) {
        const newParts = content.parts.slice();
        for (let j = 0; j < newParts.length; j++) {
          const part = newParts[j]!;
          if (part.functionCall) {
            if (!part.thoughtSignature) {
              newParts[j] = {
                ...part,
                thoughtSignature: SYNTHETIC_THOUGHT_SIGNATURE,
              };
              newContents[i] = {
                ...content,
                parts: newParts,
              };
            }
            break; // Only consider the first function call
          }
        }
      }
    }
    return newContents;
  }
```
Since I dont have access to the Gemini 3 Pro CLI at the moment, are there other contributors trying to add this logic to test?

**Comment by Mirrowel** [comment]
This is signatures i was talking about. You can easily skip it, but you still need to code the logic to do so.
It's not hard, but kilo's codebase is so massive and compilation problems alone make me not want to go in.

TLDR is you can add "skip_validation_something_something" to every first tool call of every turn to effectively pass the validation, but that will nerf the model's ability.

To do it correctly - you need to store the returne signature each time and send it back in the request(for each first tool call of every message).

UPD: Also, at least in my case, i had to force gemini 3 to send the tool calls correctly. As even with temp 1 and no overrides - it would hallucinate tool parameters. So i am not sure what is done in kilo to go around this, as it was not able to read more than one file at a time, ask followup question correctly, etc. without these changes on my end.

**Comment by Sn0wo2** [comment]
> This is signatures i was talking about. You can easily skip it, but you still need to code the logic to do so. It's not hard, but kilo's codebase is so massive and compilation problems alone make me not want to go in.
> 
> TLDR is you can add "skip_validation_something_something" to every first tool call of every turn to effectively pass the validation, but that will nerf the model's ability.
> 
> To do it correctly - you need to store the returne signature each time and send it back in the request(for each first tool call of every message).
> 
> UPD: Also, at least in my case, i had to force gemini 3 to send the tool calls correctly. As even with temp 1 and no overrides - it would hallucinate tool parameters. So i am not sure what is done in kilo to go around this, as it was not able to read more than one file at a time, ask followup question correctly, etc. without these changes on my end.

**Closing this PR for now.**
Thanks @Mirrowel and @mcowger for the testing and technical details regarding thoughtSignature.
Since I still haven't received access to the Gemini 3.0 Pro whitelist, I cannot properly debug or verify the necessary logic to handle the thought signatures and validations. As this requires more than just adding the model ID, I'll close this to avoid confusion.
Feel free to pick this up or open a new PR if you have access and the bandwidth to implement the signature logic correctly <3
